Small tweaks to FlashShape and DempoGPS
The FlashShape function overload was merged into one routine

In the compile of the Examples solution resulted in an exception for DemoGPS project: Error CS0579 Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute'.
To fix this two things were done under the project folder:
\Source\Examples\DemoGPS\
- C# (deleted this folder. looks like some remnants of the update to Core)
- c#.backup (excluded from the project tree. looks like this was the culprit as I think it was being rolled into the compilation).

Reference: https://stackoverflow.com/questions/61997928/errorcs0579duplicate-globalsystem-runtime-versioning-targetframeworkattribu
"Previously (VS 2019 and before) the project files listed all of the files that would be compiled. In VS 2022, all files in the project folder will be compiled unless they are specifically excluded in the project file."